on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    name: Pack Extension
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Add Public Key
      run: |
        cat manifest.json | jq --arg pk ${{ vars.CRX_PUBLIC_KEY }} '. + {key: $pk}' > manifest.json.tmp
        mv manifest.json.tmp manifest.json

    - name: Build
      run: |
        mkdir dist
        mkdir upload
        echo "AAAA" > upload/test.txt
        cp LICENSE manifest.json background.js dist

    - name: Pack extension
      run: |
        cd dist
        zip -r ../src.zip *

    - name: Sign Chrome Extension CRX file
      uses: cardinalby/webext-buildtools-chrome-crx-action@2.0.3
      with:
        zipFilePath: src.zip
        crxFilePath: upload/src.crx
        privateKey: ${{ secrets.CRX_PRIVATE_KEY }}
        
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v3.1.3
      with:
        name: package.crx
        path: upload/src.crx

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v0.1.15
      with:
        files: |
          upload/src.crx
          LICENSE
        generate_release_notes: true

    - name: Upload Extension to Registry
      uses: hkdobrev/minio-deploy-action@1.1.0
      with:
        endpoint: https://s3.codeths.dev
        access_key: ${{ secrets.S3_TOKEN }}
        secret_key: ${{ secrets.S3_SECRET }}
        bucket: 'ext'
        source_dir: 'upload'
        target_dir: '/dashboard'
