on:
  workflow_dispatch:

jobs:
  build:
    name: Pack Extension
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Add Public Key
      run: |
        cat manifest.json | jq --arg pk ${{ vars.CRX_PUBLIC_KEY }} '. + {key: $pk}' > manifest.json.tmp
        mv manifest.json.tmp manifest.json

    - name: Build
      run: |
        mkdir dist
        cp LICENSE manifest.json background.js dist

    - name: Pack extension
      run: |
        cd dist
        zip -r ../src.zip *

    - name: Sign Chrome Extension CRX file
      uses: cardinalby/webext-buildtools-chrome-crx-action@2.0.3
      with:
        zipFilePath: src.zip
        crxFilePath: src.crx
        privateKey: ${{ secrets.CRX_PRIVATE_KEY }}
        
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v3.1.3
      with:
        name: package.crx
        path: src.crx
