on:
  workflow_dispatch:

jobs:
  build:
    name: Pack Extension
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Pack extension
      run: zip -r src.zip ./

    - name: Sign Chrome Extension CRX file
      uses: cardinalby/webext-buildtools-chrome-crx-action@2.0.3
      with:
        zipFilePath: src.zip
        crxFilePath: src.crx
        privateKey: ${{ secrets.CRX_PRIVATE_KEY }}
