on:
  workflow_dispatch:

jobs:
  build:
    name: Pack Extension
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Chrome
      run: sudo snap install chromium

    - name: Fetch secret key
      env:
        CRX_PRIVATE_KEY: ${{ secrets.CRX_PRIVATE_KEY }}
      run: echo $CRX_PRIVATE_KEY > key.pem

    - name: Pack & Sign Extension
      run: |
        echo `ls`
        echo `pwd`
        chromium --pack-extension=./ --pack-extension-key=key.pem
