on:
  push:
    tags:
      - 'v*.*.*'
      - 'b*.*.*'

jobs:
  build:
    name: Pack Extension
    runs-on: ubuntu-latest

    strategy:
      matrix:
        environment: ${{ fromJSON( startsWith( github.ref_name, 'v' ) && '["dashboard", "dashboard-dev"]' || '["dashboard-dev"]' ) }}

    environment:
      name: ${{ matrix.environment }}

    steps:
      - uses: actions/checkout@v3

      - name: Set ENV Vars
        run: |
          echo "EXT_VERSION=${GITHUB_REF_NAME:1}" >> $GITHUB_ENV
          echo "ETHS_API_BASE=${{ vars.ETHS_API_BASE }}" >> $GITHUB_ENV
          echo "ETHS_FIREBASE_TOKEN=${{ vars.ETHS_FIREBASE_TOKEN }}" >> $GITHUB_ENV

      - name: Rename Extension
        if: ${{ matrix.environment == 'dashboard-dev' }}
        run: |
          cat manifest.json | jq '. + {name: "ETHS Tools (dev)"}' > manifest.json.tmp
          mv manifest.json.tmp manifest.json

      - name: Add Public Key & update_url
        run: |
          cat manifest.json | jq --arg pk ${{ vars.CRX_PUBLIC_KEY }} '. + {key: $pk, update_url: "https://s3.codeths.dev/ext/${{ matrix.environment }}/latest.xml"}' > manifest.json.tmp
          mv manifest.json.tmp manifest.json

      - name: Build Extension
        run: |
          npm ci
          env
          npm run build
          cp LICENSE dist

      - name: Generate latest.xml
        run: |
          mkdir upload
          awk -v ext_id="${{ vars.EXT_ID }}" -v ext_url="https://s3.codeths.dev/ext/${{ matrix.environment }}/${{ env.EXT_VERSION }}.crx" -v ext_version="${{ env.EXT_VERSION }}" \
          '{gsub(/EXT_ID/, ext_id); gsub(/EXT_URL/, ext_url); gsub(/EXT_VERSION/, ext_version); print}' update.xml > upload/latest.xml

      - name: Pack extension
        run: |
          cd dist
          zip -r ../src.zip *

      - name: Sign Chrome Extension CRX file
        uses: cardinalby/webext-buildtools-chrome-crx-action@2.0.3
        with:
          zipFilePath: src.zip
          crxFilePath: upload/${{ env.EXT_VERSION }}.crx
          privateKey: ${{ secrets.CRX_PRIVATE_KEY }}

      - name: Upload Build Artifact
        if: ${{ ! ( startsWith( github.ref_name, 'v' ) && matrix.environment == 'dashboard-dev' ) }}
        uses: actions/upload-artifact@v3.1.3
        with:
          name: ${{ github.ref_name }}.crx
          path: upload/${{ env.EXT_VERSION }}.crx

      - name: Create GitHub Release
        if: ${{ ! ( startsWith( github.ref_name, 'v' ) && matrix.environment == 'dashboard-dev' ) }}
        uses: softprops/action-gh-release@v0.1.15
        with:
          files: |
            upload/${{ env.EXT_VERSION }}.crx
            src.zip
            LICENSE
          generate_release_notes: true
          prerelease: ${{ startsWith( github.ref_name, 'b' ) }}

      - name: Upload Extension to Registry
        uses: hkdobrev/minio-deploy-action@1.1.0
        with:
          endpoint: https://s3.codeths.dev
          access_key: ${{ secrets.S3_TOKEN }}
          secret_key: ${{ secrets.S3_SECRET }}
          bucket: 'ext'
          source_dir: 'upload'
          target_dir: '/${{ matrix.environment }}'
